Unity-Technologies/com.unity.multiplayer.mlapi

- MLAPI/MonoBehaviours/Core/NetworkedBehaviour.cs
- MLAPI/MonoBehaviours/Core/NetworkingManager.cs
- MLAPI/NetworkingManagerComponents/MessageManager.cs
Targeted messages are only invoked on the network behaviours listening to it that sit on the same NetworkedObject that requested it.
> Added targeted object targeted messages

- MLAPI/MonoBehaviours/Prototyping/NetworkedAnimator.cs
Replicate HLAPI patch in https://bitbucket.org/Unity-Technologies/networking/pull-requests/21/cache-animator-parameters-to-avoid/diff
> Avoid allocations in NetworkedAnimator

- MLAPI/MonoBehaviours/Core/NetworkedBehaviour.cs
Made SyncedVar hooks fire on host as well as on clients to simplify for example, updating of UI.
> Made SyncedVar hooks fire on host aswell as on clients.

- MLAPI/MonoBehaviours/Core/NetworkedBehaviour.cs
1. Description for SendToLocalClient*() method overloads was incorrect
2. Mixed used of "gets invoked" vs "will get invoked" for *Target() methods - changed all to "will get invoked"
> Minor API documentation fixes for NetworkedBehaviour.cs

- MLAPI/Data/NetworkedVar.cs
Make NetworkedVar OnValueChanged event be called for the setter of the value as well.
> NetworkedVar OnValueChanged called for everyone

- MLAPI/MLAPI.csproj
- MLAPI/NetworkingManagerComponents/Binary/BitReader.cs
- MLAPI/NetworkingManagerComponents/Binary/BitWriter.cs
- MLAPI/NetworkingManagerComponents/Binary/IBitWritable.cs
- MLAPI/NetworkingManagerComponents/Core/NetworkSceneManager.cs
Add possibility to make simple custom types that can be handled by the BitWriter/BitReader.
This opens up possibility to add simple custom types to the default NetworkedVar system and the simple version of rpc's.
> custom types for BitWriter and BitReader

- MLAPI/NetworkingManagerComponents/Core/NetworkSceneManager.cs
get scene by name looks through scenes loaded or scenes being loaded, therefor the scene will be fetched after loading is initiated.
> fix problem with scene switching.

- MLAPI/NetworkingManagerComponents/Binary/BitReader.cs
Fix read bug where stringbuilder object is returned instead of string. Fix bug where check for if type is a IBitWritable failed and placed check for is IBitWritable last in the if chain.
> Fix two bitReader read bugs.

- MLAPI/Data/NetworkPool.cs
- MLAPI/NetworkingManagerComponents/Core/NetworkPoolManager.cs
Fix NetworkPoolManager.CreatePool so it adds created pool to Pools Dictionary
Fix NetworkPool.SpawnPooledObject condition to return pool object.
Fix NetworkPool constructor so it adds object to the objects array for the pool.
Eliminated two GetComponent calls from NetworkPool constructor.
> Fixes for null ref when spawning pooled networked objects

- MLAPI/MonoBehaviours/Prototyping/NetworkedTransform.cs
- use unscaledDeltaTime instead of time. This seems to have been broken in https://github.com/MidLevel/MLAPI/commit/c308b740e2c1e7c12fb69bbec716be3fec1cd329#diff-4940638accaf9c3627bff12a7fb2f80bL177
> Fix to NetworkedTransform

- MLAPI/Data/Transports/UNET/UnetTransport.cs
GetConfig() will try to insert already existing kvp-pairs. Clearing the dictionaries fixes this and allows, for example, doing StartHost() -> StopHost() -> StartHost() within the same session.
> fix(unet-channels): Invoking .Clear() on two Dictionaries within the Shutdown-function

- docs/_pages/features.html
Both Mirror and MLAPI support sync sets.
Note that the IList, ISet, IDictionary mentioned in #192  is no longer needed because Mirror now supports generic ILIst, ISet and IDictionary implementations too.
> docs: Add syncsets

- docs/_docs/advanced-topics/custom-transports.md
There's actually no LiteNetLib transport implemented any more.
> docs(website): Replaced LiteNetLib mentions with ENET

- docs/_docs/getting-started/installation.md
This fixes a small typo and adds more explicit details on how to get MLAPI installed (even though the gif is fairly detailed already, to have the supporting text be just as much).
Not entirely sure what changed in the last Installation line, quickly edited this using the web-based Github editor so I imagine there's some linebreak difference? (\r\n vs \n or something)
> docs(website): Clarify the Installer docs section

- MLAPI/Core/NetworkedObject.cs
Fixes a case with soft-sync or connecting without scene change where the SpawnedObjectsList is automatically assumed to be populated and have something at index zero.
> Stop NetworkedBehaviourUpdate from running if SpawnedObjectsList is empty.

- MLAPI-Editor/NetworkingManagerEditor.cs
- MLAPI/Configuration/NetworkConfig.cs
- MLAPI/Core/NetworkingManager.cs
- MLAPI/Messaging/InternalMessageHandler.cs
- MLAPI/Messaging/InternalMessageSender.cs
This PR improves `NetworkTime` handling in the following ways:
1. `NetworkTime` is derived from `Time.unscaledTime` rather than being incremented manually.  This improves accuracy when the game is moved to the background.
2. Time is synced based on `Time.realtimeSinceStartup` to best represent when the packet is actually sent and received, rather than the time at which the frame started.
3. Only half the RTT is used to offset the time received from the network, since the packet only had to travel one way.
4. Time resync packets skip the queue to avoid unnecessary delays.
5. When a time resync updates `NetworkTime`, the change is smeared over multiple frames to avoid having a very small or even negative (!) delta between consecutive values.  This can prevent some crazy bugs in user code, …
> fix(core): improve accuracy of NetworkTime and smear changes on resync.

- MLAPI/Messaging/ReflectionMethod.cs
- MLAPI/Messaging/RpcTypeDefinition.cs
Two small fixes for things that got broken when fixing styles on my previous PR:
1. You're unnecessarily allocating the `parameterTypes` array when `useDelegate` is `true`.
2. You lost `BindingFlags.DeclaredOnly` in `GetAllMethods`.  It's necessary, since you're walking the inheritance hierarchy manually and don't want to get all the methods inherited from `NetworkedBehaviour`!  Without this flag, I either get dictionary key conflicts or a super-long startup time as each type takes a few seconds to process hundreds of methods.
> fix(core): fix small bugs introduced by style fixes.

- MLAPI/Core/NetworkedObject.cs
- MLAPI/Core/NetworkingManager.cs
- MLAPI/Messaging/InternalMessageHandler.cs
- MLAPI/SceneManagement/NetworkSceneManager.cs
- MLAPI/Spawning/SpawnManager.cs
This will spawn an object under the same parent, if the parent is also a network object.  If the parent is missing, it will log an error and _not_ create the child -- we may want to log a warning and create anyway, I don't know.  Either way, this change likely breaks backwards compatibility.
I didn't add an option to specify a parent when spawning the player object, mostly because I don't use the player object myself and have no idea if that would be useful or not.
BTW, this change was a bit of a pain to write because similar pieces of code are scattered all over the place, and the code to write/read a given message isn't colocated.  Food for future refactoring, perhaps.
> fix(core): spawn objects under the correct parent.

- MLAPI/Core/NetworkingManager.cs
- MLAPI/Messaging/InternalMessageHandler.cs
- MLAPI/Transports/Transport.cs
Two main changes:
1. Fire off a separate time sync packet before the potentially big client approval message.
2. Update the `Transport` SPI to optionally provide a more precise reception time for events.
The change to `Transport ` is backwards-compatible but introduces extra complexity.  It could be simplified if you're willing to break backwards compatibility and update all the transports.
> fix(core): further improve precision of time sync.

- MLAPI/Prototyping/NetworkedTransform.cs
The channel to be used to send data for NetworkedTransforms can now be
specified. If left unspecified, the default channel is used.
> feat: Exposed channels in NetworkedTransform

- MLAPI-Editor/PostProcessScene.cs
I noticed that when hosting from the unity editor with softsync that a built version of the game could not connect. However connections between two built versions of the game (on the same build) worked fine. This was due to the editor extension producing an unreliable list of NetworkedInstanceIds. Fixing the sort of NetworkedObjects resolved the issue.
> Fix NetworkedObject sorting in editor extension 

- docs/_pages/features.html
It is a bit different from MLAPI,  so you can put a note somewhere if you like.
Mirror does it on a component by component basis  instead of a variable by variable basis.
> docs: Mirror has synctoowner

- MLAPI/Messaging/ReflectionMethod.cs
The code previously was not doing what the comment implied - it was sending the current stream, not the shortened stream containing only user data. This effectively meant that the else block was redundant and adding additional overhead.
> fix: Fixed incorrect stream usage in NetworkedBehaviour

- MLAPI/Core/NetworkedBehaviour.cs
I know this looks weird and useless, but in my project I derive all behaviors from (subclasses of) `NetworkedBehaviour` for convenience, even when they're not attached to a `NetworkedObject`.  It's thus useful to be able to check in those abstract superclasses whether the behavior is really networked or not without raising and catching an exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/midlevel/mlapi/300)
> feat(core): add NetworkedBehaviour.HasNetworkedObject getter

- MLAPI/Serialization/Pooled/BitStreamPool.cs
If we prioritize pulling from the overflow streams (as it was before), it's possible for us to retain the weak references for a lot longer than is desirable as we will keep accessing them. It's therefore preferable to return a stream from the normal queue to allow the GC time to clean the weak references, and only return an overflow value if there is no other option.
> perf: Prioritize non-weak streams over weak referenced streams.

- MLAPI/Core/NetworkingManager.cs
We need to hard-reset the network time offset every time the client connects, since there's no guarantee that it's connecting to the same server or that the server hasn't restarted.  This PR forces a hard sync on connection approval, but retains smearing of any adjustments while the connection remains up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/midlevel/mlapi/313)
> fix(core): don't smear network time adjustment on initial connection sync.

- MLAPI/Serialization/BitReader.cs
The correct formula to reconstruct w is 
> w = sqrt( 1 - x^2 - y^2 - z^2 )
but in code was
> w = sqrt(1 - x^2 + y^2 - z^2)
> fix: reader.ReadRotationPacked() "w" reconstruction

- docs/_docs/the-basics/messaging-system.md
Fixed broken lambda expression in named message example code: missing "=>".
> messaging-system.md - example code error fix

- MLAPI/Core/NetworkingManager.cs
No reason to cleaning these handlers. Now implementing own pooling system is harder because initialization must be done after ServerStart()/ClientStart()/HostStart().
> Remove cleaning custom spawn/destroy handlers

- MLAPI/Configuration/NetworkConfig.cs
Currently if 'Enable Scene Management' is set to false MLAPI prints a NetworkConfiguration
mismatch warning on connection if the server and client have a different registered scenes list.
> fix: NetworkConfig exclude registered scenes list from hash if scene managment is disabled

- com.unity.multiplayer.mlapi/Runtime/Serialization/DataStream.cs
- com.unity.multiplayer.mlapi/Runtime/Serialization/DataStream.cs.meta
- com.unity.multiplayer.mlapi/Runtime/com.unity.multiplayer.mlapi.runtime.asmdef
- com.unity.multiplayer.mlapi/Tests.meta
- com.unity.multiplayer.mlapi/Tests/Editor.meta
- com.unity.multiplayer.mlapi/Tests/Editor/DataStreamTests.cs
- com.unity.multiplayer.mlapi/Tests/Editor/DataStreamTests.cs.meta
- com.unity.multiplayer.mlapi/Tests/Editor/com.unity.mulitplayer.mlapi.editortest.asmdef
- com.unity.multiplayer.mlapi/Tests/Editor/com.unity.mulitplayer.mlapi.editortest.asmdef.meta
- com.unity.multiplayer.mlapi/package.json
This PR brings in a copy of the DataStream class from the UTP package with some modifications. It removes the NetworkCompressionModel support as well Packed support. 
While yes this is code duplication, the DataStream class in UTP is about 100x faster in testing than the current BitWriter/Reader and is job/thread safe and doesn't do any sort of managed allocations or boxing. The reason we are wanting to copy this over instead of putting it into a collection package or something is the DataStream is part of UTP which is also used for DOTS Netcode which would require a bunch of work on new packages and moving things around and bring in Network specific code into Collections which is not going to happen in the near-term. So for now to get the major perf gains this will result in code …
> feat(serialization): Bringing over the DataStream class from UTP

- .gitignore
- com.unity.multiplayer.mlapi/CHANGELOG.md
- com.unity.multiplayer.mlapi/Documentation~/Manual.md
- com.unity.multiplayer.mlapi/ValidationExceptions.json
- com.unity.multiplayer.mlapi/ValidationExceptions.json.meta
- com.unity.multiplayer.mlapi/package.json
- com.unity.multiplayer.transport.enet/CHANGELOG.md
- com.unity.multiplayer.transport.enet/Documentation~/Manual.md
- com.unity.multiplayer.transport.enet/package.json
- com.unity.multiplayer.transport.utp/CHANGELOG.md
- com.unity.multiplayer.transport.utp/Documentation~/Manual.md
- com.unity.multiplayer.transport.utp/package.json
This allows the MLAPI Package to pass validation allowing it to be published into the internal registry.
> ci: Fixes some validation issues 

- com.unity.multiplayer.mlapi/Runtime/Prototyping/NetworkedTransform.cs
Fixes a bug when EnableRange was enabled in the NetworkedTransform.
Previously, interpolation would not work because it would constantly resend the position causing snapping. This is now fixed.
> fix: Fixed transform range interpolation

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkedBehaviour.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkedObject.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkingManager.cs
- com.unity.multiplayer.mlapi/Runtime/Logging/NetworkLog.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/CustomMessageManager.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/InternalMessageHandler.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/InternalMessageSender.cs
- com.unity.multiplayer.mlapi/Runtime/SceneManagement/NetworkSceneManager.cs
- com.unity.multiplayer.mlapi/Runtime/Spawning/SpawnManager.cs
After working on the AOI stuff, it dawned on me that passing in the client object into send is less and less useful.  In fact I think we can remove it.
> refactor: internally breaking, send no longer has client obj parameter

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkedBehaviour.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkedObject.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkingManager.cs
- com.unity.multiplayer.mlapi/Runtime/NetworkedVar/NetworkedVar.cs
This change is key to allowing us to do AOI; it moves the 'for each client' to the outer loop.
> refactor: move client iteration to outermost loop

- docs/_docs/the-basics/messaging-system.md
In the page: https://mlapi.network/wiki/messaging-system/ Convenience Example section
`InvokeServerRpc(MyServerRpc, Random.Range(-50, 50));` "Rpc" throws `The name 'MyServerRpc' does not exist in the current context` and should be changed to capital letters.
> [Wiki] InvokeServerRpc(MyServerRpc, ...) changed to "MyServerRPC" 

- docs/_docs/getting-started/index.md
It was mispelling licence instead of license
> docs: replaced licence for license in getting started

- .yamato/project.metafile
- com.unity.multiplayer.mlapi/Editor/CodeGen/CodeGenHelpers.cs
- com.unity.multiplayer.mlapi/Editor/CodeGen/ILPostProcessCompiledAssembly.cs
- com.unity.multiplayer.mlapi/Editor/CodeGen/ILPostProcessCompiledAssembly.cs.meta
- com.unity.multiplayer.mlapi/Editor/CodeGen/ILPostProcessor.cs
- com.unity.multiplayer.mlapi/Editor/CodeGen/ILPostProcessor.cs.meta
- com.unity.multiplayer.mlapi/Editor/CodeGen/ILPostProcessorProgram.cs
- com.unity.multiplayer.mlapi/Editor/CodeGen/ILPostProcessorProgram.cs.meta
- com.unity.multiplayer.mlapi/Editor/CodeGen/NetworkBehaviourILPP.cs
- com.unity.multiplayer.mlapi/Editor/CodeGen/PostProcessorAssemblyResolver.cs
- com.unity.multiplayer.mlapi/Editor/CodeGen/PostProcessorReflectionImporter.cs
- com.unity.multiplayer.mlapi/Editor/CodeGen/PostProcessorReflectionImporterProvider.cs
- com.unity.multiplayer.mlapi/Editor/CodeGen/RuntimeAccessModifiersILPP.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkedBehaviour.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkingManager.cs
- com.unity.multiplayer.mlapi/package.json
IL Postprocessing has some issues in older versions of Unity where we had been running it in process VS 2020.2+ where we run it out of process which prevents some level of assembly conflicts but also has some different issues. 
This PR does a couple of things, we hook into the `CompilationPipeline `and listens for assemblies who have finished compiling and then does some checking and from there runs the `ILPostprocessor `on the assembly as it had before what makes this work is that the assembly has already been compiled thus we don't run into some of the issues we had in the past. 
This API also keeps backwards compatibility with the Unity `ILPostprocessor `API and can be disabled by setting the `USE_UNITY_ILPP `scripting define and it will flip back over to using the internal Unity one …
> refactor: ILPP workarounds for 2019.4 and 2020.2+ bugs 

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkingManager.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/InternalMessageSender.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/RPCQueue/RPCQueueProcessing.cs
- com.unity.multiplayer.mlapi/Runtime/Transports/MultiplexTransportAdapter.cs
- com.unity.multiplayer.mlapi/Runtime/Transports/Transport.cs
- com.unity.multiplayer.mlapi/Runtime/Transports/UNET/UnetChannel.cs
- com.unity.multiplayer.mlapi/Runtime/Transports/UNET/UnetTransport.cs
- com.unity.multiplayer.transport.enet/Runtime/EnetTransport.cs
Part 2 of the de-string-ification of channels
> refactor: reference channels as bytes through the transport layer

- com.unity.multiplayer.mlapi/Editor/CodeGen/NetworkBehaviourILPP.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkedBehaviour.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/RpcAttributes.cs
- com.unity.multiplayer.mlapi/Runtime/Transports/Transport.cs
- Replaces `RpcAttribute`'s `bool IsReliable` flag with `RpcDelivery` type, adds related transport-level channels.
- ~~Removes `bool RequireOwnership` flag until we (re)design ownership/control management systems.~~
- ~~_**note:** after this change, every client can execute RPCs on the server-side without having ownership._~~
- based on our discussion, we want to keep `bool RequireOwnership` flag until we have an immediate replacement. I will update this PR accordingly. (done ✔️)
> feat: RPC Delivery Types

- com.unity.multiplayer.mlapi/Editor/PostProcessScene.cs
This fixes the soft synch issue when running a host or client within the editor.
This fix is related to [Jira Task MTT-505](https://jira.unity3d.com/browse/MTT-505)
> fix: No longer re-assign network instance ids on scene load

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkTickSystem.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkTickSystem.cs.meta
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkingManager.cs
Implements the very minimal part of a tick system we need for synced networked variables.
I tried to keep it to the bare minimum and avoid any difficult design decision. This would be a first stepping stone. 
Later on, we can consider what it means to pause/resume the tick system, to scale time, etc. Tests are pending, I'll get started on them.
> feat: implement NetworkTickSystem based on NetworkUpdateLoop

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkingManager.cs
I noticed this issue when I encountered this `NullReferenceException` callstack:
- `MLAPI.NetworkingManager.OnDestroy()`
- `MLAPI.NetworkingManager.Shutdown()`
- `MLAPI.Messaging.RpcQueueContainer.Shutdown()`
- `MLAPI.Messaging.RpcQueueProcessor.InternalMessagesSendAndFlush()`
- **NullReferenceException: Object reference not set to an instance of an object**
We are making `NetworkManager.Singleton = null` then call `NetworkManager.Shutdown()` which causes this issue.
I think even regardless of this issue, we should NOT make `NetworkManager.Singleton = null` since other systems might still access the `NetworkManager` while shutting themselves down, similar to the issue we're seeing here.
> fix: do NOT call Shutdown() before Singleton = null on NetworkManager.OnDestroy()

- com.unity.multiplayer.mlapi/Editor/MLAPIProfiler.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkingManager.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/InternalMessageSender.cs
Removing the old MLAPI Profiler from UNITY_2020_2_OR_LATER in favor of using the new profiler data propagation
> refactor!: Removing the old MLAPI Profiler from UNITY_2020_2_OR_LATER

- .yamato/project.metafile
- com.unity.multiplayer.mlapi/CHANGELOG.md
- com.unity.multiplayer.mlapi/package.json
> chore: update package manifest version to 0.1.0

- com.unity.multiplayer.mlapi/Runtime/Transports/MultiplexTransportAdapter.cs
- com.unity.multiplayer.mlapi/Runtime/Transports/NetworkTransport.cs
- com.unity.multiplayer.mlapi/Runtime/Transports/UNET/UNetTransport.cs
- com.unity.multiplayer.mlapi/Tests/Runtime/RpcQueueTests.cs
This reverts commit feea3c1d4a4cfe8cfbce5ca4fa891a1787f26c88.
> revert: Add NetworkAddress and NetworkPort properties to Transport

- com.unity.multiplayer.mlapi/Runtime/AssemblyInfo.cs
currently, RuntimeTests asmdef can't access MLAPI Runtime internals which is a blocker for writing PlayMode tests
with this PR, RuntimeTests asmdef will be able to access MLAPI Runtime internals such as `InternalMessageSender`, `RpcQueueContainer` etc.
> test: expose runtime internals to runtime tests asmdef

- .yamato/project-test.yml
we should run tests on release branches over Yamato CI pipeline
> ci: enable yamato on PRs targeting master, develop and release/* branches

- .github/workflows/conventional-pr.yml
with this, conventional PR commit messages are also going to be checked on PRs targeting "release/*" branches
> ci: enable conventional PR checks on PRs targeting release branches

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
Refactor error messaging around adding/removing network prefabs from the config to be more descriptive on what you are doing wrong.
> refactor: Improve error messages for NetworkPrefab list.

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkObject.cs
- Refactors duplicate spawn code into a single function.
- Added a NotServerException when spawning an object on a client which is not supported
(Before this fix you get an unclear KeyNotFound exception when trying to spawn an object on a client)
> refactor: Refactor spawncall and improve error handling for spawning

- .yamato/project-test.yml
was missing the backslash escape character before the forwardslash :)
> fix: re-fix yamato release branch wildcard regex

- com.unity.multiplayer.mlapi/Runtime/Serialization/NetworkWriter.cs
`NetworkReader.ReadObjectPacked()` uses `ReadBool()` and this `NetworkWriter.WriteObjectPacked()` method should also use `WriteBool()` method instead of calling `WriteBit()` directly.
This was causing a serialization error because the underlying type of bool is no longer bit, it's byte now (will fix bits later).
> fix: call WriteBool instead of WriteBit on NetworkWriter.WriteObjectPacked when serializing bool object

- com.unity.multiplayer.mlapi/Editor/PostProcessScene.cs
this PR reverts (unfixes) [#493 fix: No longer re-assign network instance ids on scene load](https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi/pull/493)
it is not a proper fix and probably doesn't fix what is intended to be fixed.
we'll have another attempt to fix in the future.
> fix: (unfix) revert Application.isPlaying check in NetworkScenePostProcess

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkUpdateLoop.cs
- com.unity.multiplayer.mlapi/Tests/Runtime/NetworkUpdateLoopTests.cs
this test will verify that `NetworkUpdateLoop` injects `NetworkUpdateStage`s into Unity's low-level `PlayerLoop` at relevant places.
> test: implement test for NetworkUpdateLoop injecting NetworkUpdateStages into the PlayerLoop

- com.unity.multiplayer.mlapi/Tests/Runtime/NetworkUpdateLoopTests.cs
extending existing `NetworkUpdateLoopTests` implementation further so that it covers:
- Verify NetworkUpdateStage.FixedUpdate runs an equal number of times with MonoBehaviour.FixedUpdate
- `Assert.AreEqual(netUpdates[kNetFixedUpdateIndex], monoUpdates[kMonoFixedUpdateIndex]);`
- Verify NetworkUpdateStage.Update runs an equal number of times with MonoBehaviour.Update
- `Assert.AreEqual(netUpdates[kNetPreUpdateIndex], monoUpdates[kMonoUpdateIndex]);`
- Verify NetworkFixedUpdate runs before MonoBehaviour.FixedUpdate
- `Assert.AreEqual(monoUpdates[kMonoFixedUpdateIndex] + 1, netUpdates[kNetFixedUpdateIndex]);`
- Verify NetworkPreUpdate and NetworkUpdate runs before MonoBehaviour.Update
- `Assert.AreEqual(monoUpdates[kMonoUpdateIndex] + 1, netUpdates[kNetPreUpdateIndex]);`
- Verify …
> test: implement extra features on top of existing NetworkUpdateLoopTests to cover other test cases

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/RpcQueue/RpcQueueContainer.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/RpcQueue/RpcQueueProcessor.cs
Re-doing this a bit to separate out commits, add testing
> revert: refactor RPQQueue singleton, shutdown queue flush

- com.unity.multiplayer.mlapi/Editor/NetworkAnimatorEditor.cs
- com.unity.multiplayer.mlapi/Editor/NetworkManagerEditor.cs
- com.unity.multiplayer.mlapi/Editor/NetworkObjectEditor.cs
- com.unity.multiplayer.mlapi/Prototyping/NetworkNavMeshAgent.cs
- com.unity.multiplayer.mlapi/Runtime/Configuration/NetworkPrefab.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkBehaviour.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkObject.cs
- com.unity.multiplayer.mlapi/Runtime/Logging/NetworkLog.cs
- com.unity.multiplayer.mlapi/Runtime/Serialization/NetworkWriter.cs
- com.unity.multiplayer.mlapi/Runtime/Spawning/NetworkSpawnManager.cs
these changes should've been under an isolated PR.
I will attempt to convert them to more performant ones again in the future.
> fix: revert ReferenceEquals() checks back

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
- com.unity.multiplayer.mlapi/Runtime/Profiling/ProfilerCountersInfo.cs
If something causes an exception it's possible that the profiler never allocates data. in these cases, there is no point in sending data outside of MLAPI
> fix: prevent OnPerformanceTickData from sending data on null

- com.unity.multiplayer.mlapi/Tests/Editor/BitStreamTests.cs
- com.unity.multiplayer.mlapi/Tests/Editor/NetworkBufferTests.cs
- com.unity.multiplayer.mlapi/Tests/Editor/NetworkBufferTests.cs.meta
Expect this to fail until the fix for this has been backported to develop.
Perhaps target release?
>  test: Added regression test for BitWriter / BitReader bool size inconsistency

- com.unity.multiplayer.mlapi/Runtime/Configuration/NetworkConfig.cs
This fixes a bug which clears the NetworkPrefab list in NetworkManager when upgrading from the MLAPI version before our name changes.
> fix: networkprefab upgrade with formerlyserializedas attribute

- MLAPI/Spawning/SpawnManager.cs
I've been running into this error without knowing which object is actually triggering it. Hopefully this is helpful to others as well.
> Include instance ID in soft sync failure message

- com.unity.multiplayer.mlapi/Editor/NetworkManagerEditor.cs
- com.unity.multiplayer.mlapi/Runtime/Configuration/NetworkConfig.cs
Lag compensation was removed but config to it wasn't. This removes config for lag compensation as well which should have been done.
> feat: Remove lag compensation related stuff from config

- com.unity.multiplayer.mlapi/Runtime/Spawning/NetworkSpawnManager.cs
This is the fix for [MTT-544](https://jira.unity3d.com/browse/MTT-544) where transitioning from a scene that has InSceneObjects the Host-Server will throw an exception due to a list in the middle of an enumerative processing loop is modified.
The Jira Bug MTT-544 describes the steps to reproduce the exception and to verify this branch fixes those specific exceptions.
> fix: ServerDestroySpawnedSceneObjects throws an exception before switching scene

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkUpdateLoop.cs
- com.unity.multiplayer.mlapi/Tests/Runtime/NetworkUpdateLoopTests.cs
- implement `UnregisterLoopSystems()` to unregister systems injected into the `PlayerLoop` by the `NetworkUpdateLoop`
- implement a register-then-unregister test to verify `NetworkUpdateLoop` does NOT cause any side-effects on `PlayerLoop`
- refactor for performance (use array ops instead of lists), for better namings (inject → register) and styling (extract duplicate code into helper methods: `TryAddLoopSystem` & `TryRemoveLoopSystem`)
> fix: unregister NetworkPlayerLoop systems from PlayerLoop

- com.unity.multiplayer.mlapi/Prototyping/NetworkNavMeshAgent.cs
NetworkNavMeshAgent expects a NavMeshAgent and throws a null ref if it's not there. So this attribute should have been there to prevent user error.
> fix: Add RequireComponent attribute to NetworkNavMeshAgent.

- .yamato/project.metafile
as per our internal conversation, now targeting:
- 2019.4 LTS
- 2020.3 LTS
- 2021.1 TECH
- 2021.2 TECH
- trunk
> ci: target 2019.4 LTS, 2020.3 LTS, 2021.1 TECH, 2021.2 TECH and trunk versions

- com.unity.multiplayer.mlapi/Editor/CodeGen/NetworkBehaviourILPP.cs
> fix: implement warning logs on non-owner invoking ServerRpc that requires ownership

- README.md
Removed old mlapi.network links to api/wiki/docs and replaced with nice shiny new Multiplayer docs site links.
> docs: Updated Docs Links for new site in readme.md

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkBehaviour.cs
found this one while running through manual tests.
it occurs if you're running as a Host and trying to replicate an Unreliable ClientRpc (`[ClientRpc(Delivery = RpcDelivery.Unreliable)]`)
I re-did manual tests in various scenarios:
Server + 2 Clients
Host + 1 Client
Client -> ServerRpc -> Server
Server -> ClientRpc -> Clients
they all work fine now — fixes #637.
> fix: use specified transport channel instead of hardcoded reliablerpc channel

- com.unity.multiplayer.mlapi/CHANGELOG.md
- com.unity.multiplayer.mlapi/Tests/Runtime/NetworkUpdateLoopTests.cs
Add content from Release Notes into the package changelog for release 0.1.0.
Content includes revisions from previous reviews of release notes for new doc site. Additional revisions will be updated in this changelog and in the doc site release notes. 
Submitting as a draft, additional content will be added per feedback and issues are fixed. Feel free to assign more reviewers as needed. 
Scene mgmt has another issue to document when fixed, other items may be added through the bug bash/testing.
MTTDOC-112
> docs: added release notes to changelog.md

- com.unity.multiplayer.mlapi/Documentation~/Manual.md
resolves #553 
resolves MTT-534
> docs: Add content for mlapi manual.md

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
RpcSent, NamedMessagesSent, and UnnamedMessagesSent were broken because they are triggered from the game loop and would not be included in the profiler tick data
> fix: fixed network activity occurring outside the core update getting missed in the profiler

- com.unity.multiplayer.mlapi/Editor/CodeGen/ILPostProcessorProgram.cs
- com.unity.multiplayer.mlapi/Tests/Runtime/RpcQueueTests.cs
There is a behavior difference between 2019.4 and 2020+ codegen that essentially does checking on the existence of ILPP vs if a CodeGen assembly is present. So in order to make sure ILPP runs properly in 2019.4 from a clean import of the project we add this dummy ILPP which forces the callback to made and meets the internal ScriptCompilation pipeline requirements.
> fix: Resolve an issue where 2019.4 would not properly run ILPP with a clean import

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkObject.cs
This fixes an issue where the destroy method can get called twice on the client side after receiving a destroy object command.
This fix is pertaining to [MTT-556](https://jira.unity3d.com/browse/MTT-556)
This is a temporary fix until the spawning and de-spawning process has been fully vetted.
This fix prevents the MonoBehavior.OnDestroy method from invoking the NetworkSpawnManager.OnDestroyObject method if it does not exist in the NetworkSpawnManager.SpawnedObjects list.
> fix: destroy object spam

- com.unity.multiplayer.mlapi/Tests/Runtime/TickSystemTests.cs
backporting b2a54ec fix that went into `master` (release) back to `develop` too.
> fix: backport TickSystemTests.VerifyTickSystem() test

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
> fix: fix approval flow not being triggered for host

- com.unity.multiplayer.mlapi/Runtime/Transports/Tests/Editor/TransportTest.cs
- com.unity.multiplayer.mlapi/Runtime/Transports/UNET/UNetChannel.cs
- com.unity.multiplayer.mlapi/Runtime/Transports/UNET/UNetTransport.cs
This PR fixes the issue where you were unable to create custom channels from UI.
When you add a channel it will autogenerate an ID. If you then want to use it in the API you have to take that byte and convert it to NetworkChannel. E.g ``myNetVar.Channel = (NetworkChannel)11``
> fix: UNET transport channel UI

- com.unity.multiplayer.mlapi/Editor/CodeGen/NetworkBehaviourILPP.cs
fixes #672
basically, we're importing `INetworkSerializable::NetworkSerialize()` method of the type being referenced from external asm into the asm that uses the type in the RPC method signature.
> fix: cross-asmdef RPC ILPP

- com.unity.multiplayer.mlapi/Runtime/AssemblyInfo.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkObject.cs
this is a breaking change!
however, `NetworkInstanceId` is being used in just a few places and there is no strong reason to expose it to public.
it's more of an implementation detail that serves a purpose for identification of networkobjects placed into the scene.
> refactor!: make NetworkObject's NetworkInstanceId property internal

- com.unity.multiplayer.mlapi/Runtime/Configuration/NetworkConfig.cs
we wanted to keep this mainly for MLAPI to MLAPI-0.1.0 upgrade.
however, this is probably no longer needed for the pre-1.0.0 release.
> refactor: remove FormerlySerializedAs attribute from NetworkPrefabs field

- README.md
A dear Discord User has noticed that the MIT License hyperlink in the main README.md redirects users to a 404 page, this pull request addresses that issue.
> docs: Fix MIT license hyperlink in the main README.md

- com.unity.multiplayer.mlapi/Tests/Editor/ProfilerTests.cs
it should be under `MLAPI.EditorTests` namespace.
> chore: fix namespace for ProfilerTests

- com.unity.multiplayer.mlapi/Editor/NetworkManagerEditor.cs
- com.unity.multiplayer.mlapi/Runtime/Configuration/NetworkConfig.cs
- com.unity.multiplayer.mlapi/Runtime/Configuration/NetworkPrefab.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/InternalMessageHandler.cs
- com.unity.multiplayer.mlapi/Runtime/SceneManagement/NetworkSceneManager.cs
- com.unity.multiplayer.mlapi/Runtime/Spawning/NetworkSpawnManager.cs
- com.unity.multiplayer.mlapi/Tests/Runtime/GlobalObjectIdHash/NetworkPrefabGlobalObjectIdHashTests.cs
- com.unity.multiplayer.mlapi/Tests/Runtime/NetworkManagerHelper.cs
- testproject/Assets/ManualTests/RpcTesting.unity
This is the first pass changes required to implement MTT-640.
The default player prefab is now a directly assigned value as opposed to a checkbox in the network prefab list.
The default player prefab has to also be included in the NetworkPrefab list (this is so the default player prefab can be overridden too)
NetworkPrefab entries can be overridden and directly assigned alternate prefabs for clients to spawn.
The source prefab (what the server uses) can be a prefab reference or a prefab hash.
> feat!: Network Prefab Overrides, Inspector View, and the default Player Prefab

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkObject.cs
- com.unity.multiplayer.mlapi/Tests/Runtime/GlobalObjectIdHash/NetworkPrefabGlobalObjectIdHashTests.cs
removes `bool NetworkManager.IsTestRun` entirely as it is no longer needed.
fixes `GlobalObjectIdHash` consistency issue in the Editor (as we found with Noel during tests).
> fix: globalobjectidhash printing in editor, remove istestrun flag

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkBehaviour.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
- com.unity.multiplayer.mlapi/Runtime/Messaging/CustomMessageManager.cs
- testproject/Assets/ManualTests/Scripts/NetworkPrefabPool.cs
> // |[Comments]
> ...
> // |    - Use of #region is _always_ disallowed.
> ...
as outlined in Unity C# Coding Standards, we should never use `#region` blocks (which I also happily agree on).
currently, we have just a few, let's kill these ⚔️ before they evolve into deadly dragons 🐲 around the codebase.
> chore: remove #region blocks to better comply with coding standards

- .yamato/project-standards.yml
we ran into out-of-memory crashes during runs a few times, seems like we should upgrade to a little larger machine for this job.
> ci: upgrade standards check job's machine size to medium from small

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkObject.cs
as per our internal conversation and alignment, and as a follow-up on recent singleton removal PRs, this PR provides a minimal temporary solution to override a `NetworkObject`s `GlobalObjectIdHash` field.
this will unblock side-by-side testing in testrunner (+ over yamato ci) with multiple `NetworkManager` instances, potentially with a host/server and a client connected to it.
**this temporary solution should not be used outside unit testing scope, and it will eventually be removed completely** when we implement a similar `NetworkObject` linking feature on top of `GlobalObjectIdHash` (similar to what we had with `NetworkPrefabHandlers`) that sits a layer above `GlobalObjectIdHash` and doesn't even touch `GlobalObjectIdHash` printing logic at all.
a simple example use (pseudo-code):
```cs …
```
> feat: implement temporary globalobjectidhash override

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkObject.cs
Occasionally, we might want to call `NetworkObject.OnValidate()` method manually in an internal flow when we know exactly what we're doing.
Recently, there was a use-case where we wanted to treat `NetworkObject` instances instantiated at runtime as `NetworkPrefab`s to avoid creating more and more `NetworkPrefab` assets to get `GlobalObjectIdHash` being generated.
By allowing internal code to manually execute `NetworkObject.OnValidate()` method, we're simulating build-time/creation-time `GlobalObjectIdHash` generation at runtime — and again, in that context, we know exactly what we're doing there so that is fine.
> refactor: extract GlobalObjectIdHash generation from NetworkObject.OnValidate()

- com.unity.multiplayer.mlapi/Editor/CodeGen/NetworkBehaviourILPP.cs
Previously, `NetworkBehaviourILPP` was considering top-level types in an asmdef's main module and was trying to iterate over nested `NetworkBehaviour` derived types.
However, that approach was leaving further nested `NetworkBehaviour` types in the type hierarchy.
Switching from `ModuleDefinition.Types` to `ModuleDefinition.GetTypes()` API, `NetworkBehaviourILPP` now iterates over ALL types and filters for `NetworkBehaviour` derived types and leaving no one outside from ILPP.
> fix: NetworkBehaviourILPP to iterate over all types in an AsmDef

- com.unity.multiplayer.mlapi/Tests/Runtime/Helpers/NetworkManagerHelper.cs
During the test project unit tests experimental testing, it was discovered that some unit tests can end up in a scenario where the NetworkManager.Singleton is still the previous unit test's instance.  This assures that the NetworkManager.Singleton is the correct NetowrkManager instance upon the invocation of StartNetworkManager.
This also includes some minor style updates to the comments.
> fix: network manager helper singleton setting

- com.unity.multiplayer.mlapi/Runtime/SceneManagement/NetworkSceneManager.cs
This is a temporary solution for switching scenes during unit tests using NetworkSceneManager.  When the NetworkSceneManager is overhauled, this will probably no longer be needed.
> refactor: unit test scene transitioning

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkBehaviour.cs
- com.unity.multiplayer.mlapi/Runtime/Core/NetworkObject.cs
This PR is a follow-up of performance concerns that came up during the Snapshot System PR.
It caches in NetworkBehaviours the Id they were at, in their NetworkObject. When NetworkBehaviours don't change Id (virtually always) it skips a lookup. Improves performance, or, at the very least, alleviate concerns around performance.
Note that this is not limited to the Snapshot System. The vast majority of calls that will be made faster occur outside the SnapshotSystem
> perf: cache the behaviour id in NetworkBehaviour

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
If a network prefab is null, then it needs to only warn of the null network prefab and add it to the list of network prefabs to remove, but not try to display the non-existent prefab's name (which can cause an assert and break the initialization process).
_This was found while helping with the BossRoom upgrade to MLAPI develop branch._
> fix: Handling empty network prefab entries during NetworkManager.Init

- testproject/Assets/Scripts/GrabbableBall.cs
`GrabbableBall` used to move transform on Update() but with this PR, it will utilize transform parenting.
> feat: grabbable ball script to utilize transform parenting

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkBehaviour.cs
- com.unity.multiplayer.mlapi/Tests/Editor/NetworkBehaviourTests.cs
`NetworkBehaviour.NetworkObject` property no longer throws an exception:
- `NetworkBehaviour.NetworkObject` property getter logs a network warning and returns `null` instead.
- `NetworkBehaviour.HasNetworkObject` is now relying on `NetworkBehaviour.NetworkObject` directly.
- `NetworkBehaviourTests` are also updated accordingly.
> refactor: NetworkBehaviour.NetworkObject no longer throws exception

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
- com.unity.multiplayer.mlapi/Runtime/Spawning/NetworkSpawnManager.cs
- com.unity.multiplayer.mlapi/Tests/Runtime/ConnectionApproval.cs
- com.unity.multiplayer.mlapi/Tests/Runtime/NetworkPrefabHandlerTests.cs
- com.unity.multiplayer.transport.utp/Runtime/UTPTransport.cs
- com.unity.multiplayer.transport.utp/Runtime/Utilities.cs
- com.unity.multiplayer.transport.utp/Tests/Editor/BasicUTPTest.cs
- standards.py
we are already running `standards --check` over `Unity.Multiplayer.MLAPI*.csproj` projects.
this PR changes search glob to `Unity.Multiplayer*.csproj` and now standard check also includes UTP.
_(I also ran `standards.py --fix` locally too, all these changes are coming from that)_
> ci: enable standards check on UTP too

- com.unity.multiplayer.mlapi/Runtime/Messaging/RpcQueue/RpcQueueProcessor.cs
> fix: gracefully handle exceptions in an RPC invoke

- testproject/Assets/Tests/Runtime/RpcINetworkSerializable.cs
- testproject/Assets/Tests/Runtime/RpcINetworkSerializable.cs.meta
**Summary**
This task is to verify the user can define their own custom network serialized type.
This task is based on the following user stories:
[ MTT-787](https://jira.unity3d.com/browse/MTT-787)
[ MTT-788](https://jira.unity3d.com/browse/MTT-788)
**Acceptance Criteria**
A user should be able to implement the INetworkSerializable interface within a class and use that class as an RPC Parameter to pass between both client and server RPCs.  The test should include the reading and writing of custom values within the custom INetworkSerializable based class.
A user should be able to send arrays of the same class type that implements the INetworkSerializable interface and expect the array to maintain the exact same order from when it was sent to when it is received.
**Acceptance Tests**
From …
> test:  verifies that a user can use INetworkSerializable with RPCs

- testproject/Assets/Tests/Runtime/RpcINetworkSerializable.cs
**Summary**
This task is associated with [MTT-789]( https://jira.unity3d.com/browse/MTT-789)
This task is to convert the below Test Rail manual tests over to automated tests.
T2910451: Verify empty arrays of custom types are being serialized
T2910452: Verify null arrays of custom types are being serialized
**Acceptance Criteria**
Users should be able to send empty or null arrays for custom INetworkSerializable types. When an empty or null array is sent, the receiver should be able to receive the empty or null array.
**Acceptance Tests**
From Test Runner:
TestProject->RuntimeTests->RpcINetworkSerializable->NetworkSerializableEmptyArrayTest
TestProject->RuntimeTests->RpcINetworkSerializable->NetworkSerializableNULLArrayTest
> test: verify that empty or null arrays of custom INetworkSerializable types can be sent and received

- com.unity.multiplayer.mlapi/Runtime/Core/NetworkBehaviour.cs
- com.unity.multiplayer.mlapi/Runtime/Core/SnapshotSystem.cs
- com.unity.multiplayer.mlapi/Runtime/NetworkVariable/Collections/NetworkDictionary.cs
- com.unity.multiplayer.mlapi/Runtime/NetworkVariable/Collections/NetworkList.cs
- com.unity.multiplayer.mlapi/Runtime/NetworkVariable/Collections/NetworkSet.cs
- com.unity.multiplayer.mlapi/Runtime/NetworkVariable/INetworkVariable.cs
- com.unity.multiplayer.mlapi/Runtime/NetworkVariable/NetworkVariable.cs
- testproject/Assets/Tests/Manual/Scripts/ManualNetworkVariableTest.cs
see https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi/pull/845
Looks like the tick parameters are ignored in all impl's of ReadField() (e.g. NetworkDictionary, NetworkList, NetworkSet) with the only exception being that NetworkVariable forwards it to its LocalTick & RemoteTick variables.
LocalTick itself is never used except in ManualNetworkVariableTest.cs, which we could re-write.
RemoteTick is written to the network in NetworkBehaviour::NetworkVariableUpdate with the comment "this will allow lag-compensation".
Finally, this gets read in at NetworkBehaviour::HandleNetworkVariableDeltas, and shoved back down ReadDelta, where it is never actually used.
I sure could be missing something, but I think this may all be no op code and we can delete these parameters.
Plus all this …
> refactor!: tick param removal

- com.unity.multiplayer.mlapi/CHANGELOG.md
- com.unity.multiplayer.mlapi/Documentation~/Manual.md
Added entry to changelog.md for hotfix 0.1.1.
Added and verified links for documentation in manual.md. 
MTTDOC-262
> docs: Hotfix Changelog for 0.1.1 and manual update
