MLAPI/MLAPI.csproj, MLAPI/NetworkingManagerComponents/DiffieHellman.cs, MLAPI/NetworkingManagerComponents/EllipticCurve.cs, MLAPI/packages.config
Added PBKDF2-HMAC-SHA1
Added IntX implementation
=> Added Diffie Hellman

MLAPI/NetworkingManagerComponents/Binary/BitReader.cs, MLAPI/NetworkingManagerComponents/Binary/BitWriter.cs
Fixed various bugs
Added option to pad misalignments for improved performance (at the possible cost of compression size if called in more than one non-consecutive instance)
=> Optimized byte serialization

MLAPI.Tests/NetworkingManagerComponents/Binary/BitStreamTest.cs, MLAPI/NetworkingManagerComponents/Binary/BitStream.cs
Tests for floating point serialization
=> Add tests for floating points serialization

MLAPI.Tests/NetworkingManagerComponents/Binary/BitStreamTest.cs, MLAPI/NetworkingManagerComponents/Binary/BitStream.cs
Serialize/deserialize doubles without locks
=> Lockless doubles

MLAPI.Tests/NetworkingManagerComponents/Binary/BitStreamTest.cs, MLAPI/NetworkingManagerComponents/Binary/BitStream.cs
=> More failing tests

MLAPI/NetworkingManagerComponents/Core/InternalMessageHandler.Receive.cs
Add check for the received rpc's that it's object is in the spawned list otherwise it gets ignored.
=> Add check for the received rpc's spawned objects.

MLAPI/Data/NetworkedCollections/NetworkedList.cs
Add event for when a NetworkedList is changed, similar to unets SyncList.
=> Add event for when a NetworkedList is changed.

MLAPI/Data/Transports/UNET/UnetTransport.cs, MLAPI/MonoBehaviours/Core/NetworkingManager.cs
=> Fix for issue #164

MLAPI-Editor/NetworkedObjectEditor.cs, MLAPI-Editor/NetworkingManagerEditor.cs, MLAPI/Data/MLAPIConstants.cs, MLAPI/Data/NetworkConfig.cs, MLAPI/MonoBehaviours/Core/NetworkedBehaviour.cs, MLAPI/MonoBehaviours/Core/NetworkedObject.cs, MLAPI/MonoBehaviours/Core/NetworkingManager.cs, MLAPI/NetworkingManagerComponents/Core/InternalMessageHandler.Receive.cs, MLAPI/NetworkingManagerComponents/Core/InternalMessageHandler.Send.cs, MLAPI/NetworkingManagerComponents/Core/NetworkPoolManager.cs, MLAPI/NetworkingManagerComponents/Core/NetworkSceneManager.cs, MLAPI/NetworkingManagerComponents/Core/SpawnManager.cs, docs/_data/docs.yml, docs/_docs/the-basics/object-visibility.md, docs/_includes/docs_nav.html, docs/_includes/footer.html, docs/_pages/features.html
Clients are no longer aware of other clients, they are only aware of other objects. And objects can be shown or hidden on a object to object basis.
=> Added Visibility System

docs/_pages/features.html
Mirror now supports syncdictionaries  and multiplex transport
=> docs: update Mirror features

MLAPI/MonoBehaviours/Core/NetworkedObject.cs, MLAPI/MonoBehaviours/Core/NetworkingManager.cs, MLAPI/NetworkingManagerComponents/Core/InternalMessageHandler.Receive.cs, MLAPI/NetworkingManagerComponents/Core/NetworkSceneManager.cs, MLAPI/NetworkingManagerComponents/Core/SpawnManager.cs
Readd the ability for spawned networked objects to be removed together with the scene.
=> Readd DestroyWithScene

MLAPI-Editor/MLAPIEditor.cs
WWW class replaced with UnityWebRequest to get rid of annoying warnings inside the console.
=> refactor: Updated WWW to UnityWebRequest (MLAPIEditor.cs)

MLAPI/NetworkingManagerComponents/Core/NetworkSceneManager.cs
=> Make sure Start is only called once the old scene is unloaded

MLAPI/MonoBehaviours/Core/NetworkingManager.cs
=> Fixed method signature for custom messages.

docs/_data/docs.yml, docs/_docs/getting-started/connection-approval.md, docs/_docs/the-basics/messaging-system.md, docs/_docs/troubleshooting/common-mistakes.md
Fixed some typos / broken code examples and added a troubleshooting section with a first entry.
=> Improved Docs

.editorconfig
This is my best guess at your preferred settings...
=> chore(core): add .editorconfig.

MLAPI/Core/NetworkingManager.cs, MLAPI/Serialization/BitStream.cs
=> fix: Removed alloc HandleIncomingData

docs/_pages/features.html
https://mirror-networking.com/xmldocs/Guides/Authentication.html
=> docs: Mirror has connection approval

docs/_pages/features.html
https://mirror-networking.com/profiler/
=> docs: Mirror has a profiler

docs/_pages/features.html
Documentation here:
https://mirror-networking.com/xmldocs/Guides/DataTypes.html
=> docs: Mirror has custom rpc parameters

docs/_docs/the-basics/object-ownership.md
=> docs: Fixed spelling

MLAPI/LagCompensation/LagCompensationManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/midlevel/mlapi/314)
=> feat(lag): add method to simulate a subset of tracked objects.

docs/_docs/the-basics/networkedvar.md
Updated NetworkedVar documentation to emphasis the default ownership.
I would probably also write why it is the default and if the write permission can be changed after initalization, I lack knowledge to do that however.
I am new to this project so I am aware I might be not using the correct terminology.
Criticism welcome.
=> Updated NetworkedVar documentation

MLAPI/Spawning/SpawnManager.cs
=> fix: Riv fox/patch 1

docs/_docs/troubleshooting/common-mistakes.md
Add [`NullReferenceException` when trying to send an RPC to the server]
=> docs: Update common-mistakes.md

docs/_docs/advanced-topics/custom-transports.md
=> custom-transports.md - fixed a simple typo

docs/_docs/the-basics/object-spawning.md
=> object-spawning.md - fixed a simple typo

docs/_docs/the-basics/networkedvar.md
=> docs: Update networkedvar.md

MLAPI/Messaging/CustomMessageManager.cs, docs/_docs/advanced-topics/bitwriter-bitreader-bitstream.md, docs/_docs/core-components/networked-object.md, docs/_docs/getting-started/connection-approval.md, docs/_docs/getting-started/installation.md, docs/_docs/getting-started/library-initialization.md
Just a few small additions to the docs as I go through them to learn. Loving the API so far!
=> docs: fixed some typos, added some links, added prefab hash info

docs/_docs/getting-started/library-initialization.md
Add using declarations to initilization readme
=> Add using declarations to initilization readme

com.unity.multiplayer.transport.utp/README.md
Updating the UTP Transport package readme with proper name as well as comment about being WIP and should not be taken for anything other than a prove of concept.
=> Updating the utp package readme

docs/_docs/the-basics/networkedvar.md
=> Fixed typo in networkedvar.md

docs/_docs/the-basics/messaging-system.md
=> Documentation type miss MyServerRpc → MyServerRPC

README.md
Added multiplayer forum button.
=> docs: Updated README.md with correct links

MLAPI/NetworkedVar/Collections/NetworkedDictionary.cs, MLAPI/NetworkedVar/Collections/NetworkedList.cs
This backports the fix from PR #458 to master.
=> fix: backports a fix to networkedlist/dictionary from #458

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/feedback.md, .github/ISSUE_TEMPLATE/other-issues.md, .github/ISSUE_TEMPLATE/rfc-tracking-issue.md, .github/ISSUE_TEMPLATE/support.md
- Updated labels of Feedback templates
- Added Other Issues, Support, Feedback and RFC Tracking Issue templates
- Added links to docs, forums and discord
=> docs: Update issue templates

.github/workflows/conventional-pr.yml, .yamato/project-test.yml, com.unity.multiplayer.mlapi/Editor/PostProcessScene.cs, com.unity.multiplayer.mlapi/Runtime/AssemblyInfo.cs, com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs, com.unity.multiplayer.mlapi/Runtime/Core/NetworkObject.cs, com.unity.multiplayer.mlapi/Runtime/Core/NetworkUpdateLoop.cs, com.unity.multiplayer.mlapi/Runtime/Profiling/ProfilerCountersInfo.cs, com.unity.multiplayer.mlapi/Runtime/Serialization/NetworkWriter.cs, com.unity.multiplayer.mlapi/Runtime/Spawning/NetworkSpawnManager.cs, com.unity.multiplayer.mlapi/Tests/Runtime/NetworkUpdateLoopTests.cs
Merging updates from release/0.1.0
=> chore: merge release0.1.0 back to mainline

com.unity.multiplayer.mlapi/Runtime/Core/NetworkManager.cs
=> fix: Mark Scene dirty when automatically adding a scene to the scene list

com.unity.multiplayer.mlapi/Editor/NetworkManagerEditor.cs
=> fix: fix multiple player prefab checked

.github/ISSUE_TEMPLATE/bug_report.md
We want to know the actual behavior as well
=> docs: add "expected outcome" section to bug report template

testproject/Packages/packages-lock.json
after `testproject/Packages/manifest.json` changes went under PR #736, I think `testproject/Packages/packages-lock.json` also needs to be updated.
=> chore: update testproject/packages-lock.json

.yamato/_triggers.yml
FYI: @JesseOlmer @mattwalsh-unity @wackoisgod
=> fix: run testproject tests on PR trigger

com.unity.multiplayer.mlapi/Tests/Runtime/NetworkObjectSceneSerializationTests.cs
This cleans up the network objects instantiated at the end of the test so they don't hang around in the test runner temporary scene.
This includes minor comment style updates.
=> refactor: remove instantiated GameObjects at the end of the test

testproject/Assets/Prefabs/PlayerCube.prefab, testproject/Assets/Scenes/SampleScene.unity, testproject/Assets/Scripts/GrabbableBall.cs, testproject/Assets/Scripts/GrabbableBall.cs.meta
PR adds `GrabbableBall` object into `SampleScene` in `testproject` alongside with `GrabbableBall` script.
it will be used to test grab/ungrab mechanics in multiplayer.
=> feat: add GrabbableBall to SampleScene in testproject

testproject/Assets/Tests/Manual/Scripts/BandwidthTest.cs, testproject/Assets/Tests/Manual/Scripts/ConnectionApprovalComponent.cs, testproject/Assets/Tests/Manual/Scripts/GenericNetworkObjectBehaviour.cs, testproject/Assets/Tests/Manual/Scripts/IPlayerMovement.cs, testproject/Assets/Tests/Manual/Scripts/ManualNetworkVariableTest.cs, testproject/Assets/Tests/Manual/Scripts/NetworkPrefabPool.cs, testproject/Assets/Tests/Manual/Scripts/NetworkSceneManagerCallbackTests.cs, testproject/Assets/Tests/Manual/Scripts/PlayerColor.cs, testproject/Assets/Tests/Manual/Scripts/PlayerMovementManager.cs, testproject/Assets/Tests/Manual/Scripts/RandomMovement.cs, testproject/Assets/Tests/Manual/Scripts/RpcQueueManualTests.cs, testproject/Assets/Tests/Manual/Scripts/StatsDisplay.cs, testproject/Assets/Tests/Manual/Scripts/StatsInfoContainer.cs, testproject/Assets/Tests/Manual/Scripts/SwitchSceneHandler.cs, testproject/Assets/Tests/Runtime/SceneLoadingTest.cs
wrapping test scripts in testproject into relevant namespaces (mostly for optics and point of reference for further test scripts)
=> chore: update namespaces in testproject test scripts
